<?php

namespace core\user\controllers;

class IndexTestController extends BaseUser
{
protected function inputData()
{
    parent::inputData(); // TODO: Change the autogenerated stub

    echo $this->getController();

    exit();
}
}